Introducing chars left counter
livechat/design-system pull request #234
Opened 2021-04-30 09:55 UTC by dprzybylek

Chars left counter will be helpful to show how many chars are left in inputs with `maxlength` defined.
Value change should be handled by `onChange` method, in the same way as validation functions. `maxLength` is also passed to html input, to prevent exceeding the chars limit.
![image](https://user-images.githubusercontent.com/24878280/116679123-6e993180-a9aa-11eb-8be4-778abfb642ba.png)

2021-05-04 10:04 UTC, kamilmateusiak commented on packages/design-system/src/components/InputField/InputField.md
> +      chars: 5 - e.target.value.length
I think the example is not working correctly. https://www.figma.com/file/KCYyNivnhN4wSDOM0Qjas4/KnowledgeBase-onboarding?node-id=845%3A6022 - here we have ie. 13/20 - that means that 13 characters were used. In your example it's the opposite - you are showing how many chars are left which doesn't feel intuitive imho

2021-05-04 10:09 UTC, kamilmateusiak commented on packages/design-system/src/components/TextField/style.scss
> +  &__label-charsCounter {
<img width="343" alt="Design System - LiveChat API Developers Docs and Guides 2021-05-04 12-05-17" src="https://user-images.githubusercontent.com/24607370/116988999-7706aa80-acd1-11eb-8cd7-8570de019e22.png">
I aksed Jo about this - both labelAdornment and new element should be positioned with `flex-end`

2021-05-04 10:14 UTC, kamilmateusiak commented on packages/design-system/src/components/InputField/InputField.js
> +    charsLeft,
I asked Justyna about the [design](https://www.figma.com/file/KCYyNivnhN4wSDOM0Qjas4/KnowledgeBase-onboarding?node-id=845%3A6022). It looks like on the right it should be possible to add also something different (ie. link) so those props looks not right. 

How about a different approach - let's start exporting hooks from the library! `useUsedCharactersCounter` hook seems awesome imho. You could use it in your app and pass the prepared text to the component with new props `labelRightNode`. How it sounds?

2021-05-04 10:16 UTC, kamilmateusiak requested changes
It would be awesome to try a different approach here. I can't wait to see what you think about it :)

2021-05-06 11:53 UTC, jdrzejb commented
The current implementation forces you to use the counter with the input, the counter is not reusable in other components (like textarea), and you cannot use the top-right area to display anything else in the input.

2021-05-07 11:40 UTC, dprzybylek commented
Update: no hooks. After discuss we don't see any reason to add custom hook 🙈

2021-05-13 07:50 UTC, kamilmateusiak commented on packages/design-system/src/components/TextField/style.scss
> +  &__label-leftNode {
```suggestion
  &__label-right-node {
```
xD

2021-05-13 07:50 UTC, kamilmateusiak commented on packages/design-system/src/components/TextField/style.scss
> +    justify-content: flex-end;
add `align-self: flex-end;`

2021-05-13 07:50 UTC, kamilmateusiak commented on packages/design-system/src/components/TextField/style.scss
> +    justify-content: flex-end;
add `align-self: flex-end;`

2021-05-13 08:20 UTC, kamilmateusiak commented on packages/design-system/src/components/InputField/InputField.js
> +  labelRightNode: PropTypes.node,
could you please add those new props to forms.d.ts file with type declarations?

2021-05-13 08:21 UTC, kamilmateusiak requested changes
the component api looks good now but it requires css and typescript fixes

2021-05-14 14:11 UTC, merged