set zindex on popover
livechat/design-system pull request #398
Opened 2022-08-26 13:44 UTC by MichalPaszowski

Resolves: #[332](https://github.com/livechat/design-system/issues/332)

## Description
It seems to be enough to fix stuff like:
https://monosnap.com/file/agb5EyL9CrbJqO8E0vNQhtUAo6BYOo

## Storybook
https://feature-{issue-number}--613a8e945a5665003a05113b.chromatic.com/

## Checklist

**Obligatory:**

- [x] Self-review
- [ ] Unit & integration tests
- [ ] Storybook cases
- [ ] Design review
- [ ] Functional (QA) review

**Optional:**

- [ ] Accessibility cases (keyboard control, correct HTML markup, etc.)

2022-08-29 08:24 UTC, sgraczyk commented on packages/react-components/src/components/Popover/Popover.module.scss
> +  z-index: 1000;
Could we use a dedicated variable from
https://github.com/livechat/design-system/blob/39fcca44937242ba3bd3bc7c8b855269d335b2f1/packages/react-components/src/utils/StackingContextLevel.scss

I believe we would need to introduce a new level:

W could follow this concept from LiveChat's Agent App:

```ts
export enum StackingContextLevel {
  Tooltip = 1000,
  Dropdown = 2000,
  ...
}
```

2022-09-05 09:54 UTC, jpyzio123 approved these changes

2022-09-05 12:35 UTC, sgraczyk commented on packages/react-components/src/components/Popover/Popover.module.scss
> +  z-index: $stacking-context-level-popover;
You need to import it before usage `@import '../../utils/StackingContextLevel';`

2022-09-05 12:35 UTC, sgraczyk requested changes
Build fails, the variable is not imported

2022-09-09 10:24 UTC, sgraczyk approved these changes

2022-09-09 12:24 UTC, merged