textarea component
livechat/design-system pull request #442
Opened 2022-10-07 13:33 UTC by marcinsawicki

Resolves: #404

## Description

## Storybook
https://feature-{issue-number}--613a8e945a5665003a05113b.chromatic.com/

## Checklist

**Obligatory:**

- [ ] Self-review
- [ ] Unit & integration tests
- [ ] Storybook cases
- [ ] Design review
- [ ] Functional (QA) review

**Optional:**

- [ ] Accessibility cases (keyboard control, correct HTML markup, etc.)

2022-10-14 11:04 UTC, MichalPaszowski approved these changes

2022-11-15 13:53 UTC, jpyzio123 commented
Design also includes few different border styles which seem to be missing 
<img width="1540" alt="Product Components – Figma 2022-11-15 14-52-10" src="https://user-images.githubusercontent.com/46003125/201936385-93d193f6-3a52-407a-a8d8-47cd19b6b79d.png">

2022-11-16 12:31 UTC, kstvsko requested changes
I agree with the comments left by @jpyzio123, regarding the resizing option I think we should limit it somehow because now I can even make it smaller than the text inside.
<img width="175" alt="image" src="https://user-images.githubusercontent.com/109948903/202181247-926eacaf-c5f9-4105-8e18-eca202b0a0ca.png">

2022-11-18 11:18 UTC, kstvsko approved these changes

2022-11-18 11:52 UTC, jpyzio123 approved these changes

2022-11-18 11:54 UTC, merged